version: '3.8'

services:
  movecostinfo:
    image: shinhyeok22/movecostinfo:latest
    container_name: movecostinfo
    ports:
      - "8085:8080"
    environment:
      - JAVA_OPTS=-XX:+UseSerialGC -Xms128m -Xmx256m -Xss512k
    restart: always
