gg:
  jte:
    usePrecompiledTemplates: false
    developmentMode: true # Set to true for local development if not using precompiled templates
spring:
  application:
    name: FirstRentVerdict
# server:
#   servlet:
#     context-path: /RentVerdict
